apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: 359322168451.dkr.ecr.us-west-2.amazonaws.com/capstone:frontend
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 80
          protocol: TCP